export '../pages/about/page.dart';
export '../pages/drawer/view.dart';
export '../pages/home/view.dart';
export '../pages/mushaf/view.dart';
export '../pages/splash/view.dart';
export '../pages/statistics/view.dart';
export '../pages/app/app.dart';
export '../pages/tafseer/view.dart';
export '../pages/release_notes/view.dart';