export '../pages/about/page.dart';
export '../pages/drawer/page.dart';
export '../pages/home/page.dart';
export '../pages/mushaf/page.dart';
export '../pages/splash/page.dart';
export '../pages/statistics/page.dart';
export '../pages/app/app.dart';
export '../pages/tafseer/page.dart';
export '../pages/release_notes/page.dart';