name: yatadabaron
description: Quran Search Engine and Statistics.

version: 0.0.0+0

environment:
  sdk: ">=2.12.0 <3.7.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  rxdart: ^0.27.1
  fl_chart: ^0.62.0
  path_provider: ^2.0.2
  share: ^2.0.4
  launch_review: ^3.0.1
  package_info: ^2.0.2
  scrollable_positioned_list: ^0.3.5
  just_audio: ^0.9.32
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.6
  http: ^0.13.3
  firebase_core: ^2.4.0
  archive: ^3.1.2
  simply: ^6.0.0
  connectivity_plus: ^2.3.0
  url_launcher: ^6.1.10
  cloud_firestore: ^4.2.0
  firebase_app_check: ^0.1.1+7
  firebase_analytics: ^10.1.0
  wakelock: ^0.6.2
    
publish_to: none
flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/quran_usmani.db
    - assets/imgs/home.jpg
  fonts:
    - family: Usmani
      fonts:
        - asset: assets/fonts/UthmanicHafs1 Ver16.ttf
    - family: Emla2y
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
