export 'package:Yatadabaron/application/analytics/interface.dart';
export 'package:Yatadabaron/application/core/interface.dart';
export 'package:Yatadabaron/application/configurations/interface.dart';
export 'package:Yatadabaron/application/user-data/interface.dart';
export 'package:Yatadabaron/application/analytics/factory.dart';
export 'package:Yatadabaron/application/core/factory.dart';
export 'package:Yatadabaron/application/configurations/factory.dart';
export 'package:Yatadabaron/application/user-data/factory.dart';
export 'package:Yatadabaron/application/service-manager.dart';
