// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRL4y0MGAsyDX7eS9ffsov7QygAHO_9wA',
    appId: '1:820626362018:web:e581fe23ee4cab94c211fb',
    messagingSenderId: '820626362018',
    projectId: 'yatadabaron-8406e',
    authDomain: 'yatadabaron-8406e.firebaseapp.com',
    databaseURL: 'https://yatadabaron-8406e.firebaseio.com',
    storageBucket: 'yatadabaron-8406e.appspot.com',
    measurementId: 'G-JPX0QV0M0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxFb4T4qKsXQRalO6fDAC73wiEtFN9T7c',
    appId: '1:820626362018:android:76085a67c716a710',
    messagingSenderId: '820626362018',
    projectId: 'yatadabaron-8406e',
    databaseURL: 'https://yatadabaron-8406e.firebaseio.com',
    storageBucket: 'yatadabaron-8406e.appspot.com',
  );
}
