name: deploy-flutter-googleplay-fastlane

on:
  push:
    tags: 
      - 'test@*'
      - 'prod@*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extracting Stage, Version and Build Number
        id: gitinfo
        run: |
          tag_name=${GITHUB_REF##*/}
          tag_name_splitted=(${tag_name//@/ })
          echo Tag Name=${tag_name}
          stage=${tag_name_splitted[0]}
          version=${tag_name_splitted[1]}
          buildNumber=${tag_name_splitted[2]}
          echo stage=$stage, version=$version, build_number=$buildNumber
          echo "::set-output name=stage::$stage"
          echo "::set-output name=version::$version"
          echo "::set-output name=buildNumber::$buildNumber"
      
      - name: Preparing Secret Keys
        id: gitsecrets
        run: |
          stg=${{steps.gitinfo.outputs.stage}}
          stg=${stg^^}
          echo "::set-output name=KEYSTORE_ALIAS::${stg}_KEYSTORE_ALIAS"
          echo "::set-output name=KEYSTORE_STORE_PASSWORD::${stg}_KEYSTORE_STORE_PASSWORD"
          echo "::set-output name=KEYSTORE_KEY_PASSWORD::${stg}_KEYSTORE_KEY_PASSWORD"
          echo "::set-output name=KEYSYORE_CONTENT_BASE64::${stg}_KEYSYORE_CONTENT_BASE64"
          echo "::set-output name=STORE_SECRET_JSON::${stg}_STORE_SECRET_JSON"

      - name: Creating Keystore file
        run: |
          cd android  
        
          cd app
          keyFileAsc=key.asc
          keyFile=key.jks
          echo "${{secrets[steps.gitsecrets.outputs.KEYSYORE_CONTENT_BASE64]}}">$keyFileAsc
          gpg -d --passphrase "${{secrets[steps.gitsecrets.outputs.KEYSTORE_STORE_PASSWORD]}}" --batch $keyFileAsc > $keyFile

          cd ../
          keyPropFile=key.properties
          touch $keyPropFile
          echo keyAlias=${{secrets[steps.gitsecrets.outputs.KEYSTORE_ALIAS]}}>$keyPropFile
          echo keyPassword=${{secrets[steps.gitsecrets.outputs.KEYSTORE_KEY_PASSWORD]}}>>$keyPropFile
          echo storePassword=${{secrets[steps.gitsecrets.outputs.KEYSTORE_STORE_PASSWORD]}}>>$keyPropFile
          echo storeFile=$keyFile>>$keyPropFile

      - name: Creating Version file
        run: |
          pwd
          cd android
          verPropFile=version.properties
          touch $verPropFile
          echo flutter.versionName=${{steps.gitinfo.outputs.version}}>$verPropFile
          echo flutter.versionCode=${{steps.gitinfo.outputs.buildNumber}}>>$verPropFile

      - name: Creating Store Secret file
        run: |
          pwd
          cd android
          touch secret.json
          echo "${{secrets[steps.gitsecrets.outputs.STORE_SECRET_JSON]}}" >> secret.json

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Fastlane dependencies
        run: |
          pwd
          cd android
          bundle install
          bundle fastlane 
          cat secret.json
          fastlane run validate_play_store_json_key

      
      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'


      - name: "Setup Flutter"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.3'


      - name: Build & Deploy
        run: |
          pwd
          cd android
          flutter build apk --release
          bundle exec fastlane deploy_alpha